\LoadClass[10pt,a4paper,sans]{moderncv}% possible options include font size ('10pt', '11pt' and '12pt'), paper size ('a4paper', 'letterpaper', 'a5paper', 'legalpaper', 'executivepaper' and 'landscape') and font family ('sans' and 'roman')


% moderncv themes
\moderncvstyle{banking}                            % style options are 'casual' (default), 'classic', 'oldstyle' and 'banking'
\moderncvcolor{blue}                                % color options 'blue' (default), 'orange', 'green', 'red', 'purple', 'grey' and 'black'
%\renewcommand{\familydefault}{\sfdefault}         % to set the default font; use '\sfdefault' for the default sans serif font, '\rmdefault' for the default roman one, or any tex font name
%\nopagenumbers{}                                  % uncomment to suppress automatic page numbering for CVs longer than one page


% character encoding
\RequirePackage[utf8]{inputenc}          
\RequirePackage{geometry} % changes margins across the page
 \geometry{
 left=12mm,
 right=12mm,
 top=4mm,
 bottom=6mm,
}
\RequirePackage{amssymb}

% personal data
\name{Christian Santiago}{Haug}
%\title{Resumé title}                               % optional, remove / comment the line if not wanted

\address{4108 McQueen Drive}{Durham, North Carolina, 27705}{USA}% optional, remove / comment the line if not wanted; the "postcode city" and and "country" arguments can be omitted or provided empty
\phone[mobile]{+1~(984)~209~8836}                   % optional, remove / comment the line if not wanted
\email{c.s.haug@lse.ac.uk}                               % optional, remove / comment the line if not wanted
\homepage{christianhaug.com}                         % optional, remove / comment the line if not wanted
\social[github][github.com/chrizzzer]{github.com/chrizzzer}
\social[linkedin][linkedin.com/in/christianshaug]{linkedin.com/in/christianshaug}
